name       : perl-xmlsimple
version    : 2.22
release    : 5
source     :
    - http://search.cpan.org/CPAN/authors/id/G/GR/GRANTM/XML-Simple-2.22.tar.gz : b9450ef22ea9644ae5d6ada086dc4300fa105be050a2030ebd4efd28c198eb49
license    :
    - Artistic-Perl-1.0
summary    : Simple XML access for Perl
component  : programming.perl
description: |
    The XML::Simple module is a Perl extension that provides an easy API to read and write XML (especially config files).
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
