name       : perl-xmlsimple
version    : '2.24'
release    : 6
source     :
    - http://search.cpan.org/CPAN/authors/id/G/GR/GRANTM/XML-Simple-2.24.tar.gz : 9a14819fd17c75fbb90adcec0446ceab356cab0ccaff870f2e1659205dc2424f
license    : Artistic-Perl-1.0
summary    : Simple XML access for Perl
component  : programming.perl
description: |
    The XML::Simple module is a Perl extension that provides an easy API to read and write XML (especially config files).
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
