name       : perl-xmlsimple
version    : '2.25'
release    : 10
source     :
    - https://cpan.metacpan.org/authors/id/G/GR/GRANTM/XML-Simple-2.25.tar.gz : 531fddaebea2416743eb5c4fdfab028f502123d9a220405a4100e68fc480dbf8
license    : Artistic-Perl-1.0
component  : programming.perl
summary    : Simple XML access for Perl
description: |
    The XML::Simple module is a Perl extension that provides an easy API to read and write XML (especially config files).
builddeps  :
    - perl-xml-namespacesupport
    - perl-xml-sax-expat
    - perl-xml-sax
rundeps    :
    - perl-xml-namespacesupport
    - perl-xml-sax-expat
    - perl-xml-sax
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
